### ISSUE TITLE
Guild count not showing on tooltip 

### ISSUE THREAD

**Issue by thegamer1983** [teelolws/Altoholic-Retail#18]
The item count in the guild bank isn't showing on the tooltip even with the option enabled. 

Any help would be much appreciated. Here is a screenshot of the guild bank tab and the tooltip options window.
![WoWScrnShot_040220_132621](https://user-images.githubusercontent.com/28402341/78284953-c1719280-74e5-11ea-9310-65a632eba3cd.jpg)
![WoWScrnShot_040220_132807](https://user-images.githubusercontent.com/28402341/78284999-d51cf900-74e5-11ea-9e35-96fdcd965ba5.jpg)

Thanks

**Comment by teelolws** [comment]
This is a fix for the gbank window being empty: https://github.com/teelolws/Altoholic-Retail/commit/6360950288e679f4336661b25c0c3240c7a343e1

I couldn't replicate the no items on tooltip issue. Do you have one of the "hide this guild on the tooltip" options selected?
![image](https://user-images.githubusercontent.com/49792789/78294181-6479e900-7586-11ea-8652-ab85fa2dc069.png)

**Comment by thegamer1983** [comment]
How do I bring up that menu?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by teelolws** [comment]
Allright, grab the latest addon files off the main project page here, and give it a try.

![image](https://user-images.githubusercontent.com/49792789/78298066-7d39cd00-758d-11ea-8795-65f22da68343.png)

Fixed a bug that was stopping the Guild Bank showing if you're on a character that isn't in a guild.

**Comment by thegamer1983** [comment]
Internal server error when I try to download

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by thegamer1983** [comment]
Alright, still not working even with disabling all other addons. Take a look at this screenshot.
![WoWScrnShot_040220_162420](https://user-images.githubusercontent.com/28402341/78301324-83cd3380-74fe-11ea-80ad-74a7298c2503.jpg)

**Comment by teelolws** [comment]
Is that after clicking the Guild tab in Altoholic? Mine says disabled until I use the Guild tab at least once after a /reload.

![image](https://user-images.githubusercontent.com/49792789/78301605-d60d6380-7595-11ea-9773-6bd2d4cbe40a.png)

**Comment by thegamer1983** [comment]
using the new files got me this
![WoWScrnShot_040220_163913](https://user-images.githubusercontent.com/28402341/78302526-8fb9f500-7500-11ea-94df-9f37dcfea1e7.jpg)

**Comment by teelolws** [comment]
You have to open the addon for those to change from Disabled.

**Comment by thegamer1983** [comment]
Ok, still not working tried doing the /reload 
![WoWScrnShot_040220_165411](https://user-images.githubusercontent.com/28402341/78303599-9b0e2000-7502-11ea-8691-3b1140ff960f.jpg)

**Comment by thegamer1983** [comment]
after using each tab once memory use shows all in green, but still no listing for items in the guild when i mouseover an item on actionbar or in my bags
![WoWScrnShot_040220_170006](https://user-images.githubusercontent.com/28402341/78304240-e674fe00-7503-11ea-859d-bb333d63b053.jpg)

**Comment by teelolws** [comment]
Okay, can you upload your Altoholic and DataStore Saved Variables from here (zip them up):

![image](https://user-images.githubusercontent.com/49792789/78305065-8d0cdd80-759c-11ea-80c2-fb4774208d85.png)

**Comment by thegamer1983** [comment]
[SavedVariables.zip](https://github.com/teelolws/Altoholic-Retail/files/4424019/SavedVariables.zip)

**Comment by teelolws** [comment]
Theres no data about your guild bank. Have you actually opened the guild bank? Do you get any LUA errors when you do? Make sure you have LUA errors enabled:

/console scriptErrors 1

**Comment by thegamer1983** [comment]
yes i have opened the guild bank and clicked on each tab. No LUA errors when i open the bank

**Comment by teelolws** [comment]
Well, I tried using your Saved Variables. I went to the guild bank first, then I opened up Altoholic, and it showed my guild bank just fine.

I'd like you to try a special debug version I've made. Install this into Interface\AddOns\DataStore_Containers\

[DataStore_Containers.zip](https://github.com/teelolws/Altoholic-Retail/files/4424243/DataStore_Containers.zip)

Once you've done that, restart the game. Open your guild bank. It will dump a bunch of messages into your chat window. Screenshot the first 8 or so lines and post them here.

**Comment by teelolws** [comment]
I found the problem. Your guild is on a different server to your character, and the addon got confused while scanning the gbank.

Made a simple fix for it: https://github.com/teelolws/Altoholic-Retail/commit/83feb650f7da2c68bc8a2e86bb6bb61860d8daa7

Grab it off the main page like before.

**Comment by thegamer1983** [comment]
thanks for the help signed up on Patreon.

**Comment by thegamer1983** [comment]
still not sho
