### ISSUE TITLE
"Also Search Descriptions" search causes a Lua error

### ISSUE THREAD

**Issue by fzarr** [teelolws/Altoholic-Retail#48]
Steps: Click Search Tab, Select 'Also Search...' checkbox, type in search term and click Search.

Think it might be due to a particular item I have?

Full stack trace:

Message: Interface\AddOns\Altoholic\ItemFilters.lua:61: Usage: AltoScanningTooltip:SetHyperlink(link)
Time: Thu Jun 18 15:03:19 2020
Count: 1
Stack: Interface\AddOns\Altoholic\ItemFilters.lua:61: Usage: AltoScanningTooltip:SetHyperlink(link)
[string "@Interface\AddOns\Altoholic_Search\Search.lua"]:654: in function <Interface\AddOns\Altoholic_Search\Search.lua:638>
[string "@Interface\AddOns\Altoholic_Search\Search.lua"]:706: in function <Interface\AddOns\Altoholic_Search\Search.lua:676>
[string "@Interface\AddOns\Altoholic_Search\Search.lua"]:765: in function <Interface\AddOns\Altoholic_Search\Search.lua:762>
[string "@Interface\AddOns\Altoholic_Search\Search.lua"]:869: in function `FindItem'
[string "*:OnEnterPressed"]:2: in function <[string "*:OnEnterPressed"]:1>

Locals: item = 463280
itemCount = 1
itemLink = "[Umbrafen Spore]"
isBattlePet = "|Hbattlepet:"
MYTHIC_KEYSTONE = 138019
filters = <table> {
 SetFilterValue = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:111
 TryFilter = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:159
 ItemPassesFilters = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:129
 ClearSearchedItem = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:183
 ClearFilters = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:155
 SetSearchedItem = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:166
 GetFilterValue = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:115
 GetSearchedItemInfo = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:179
 EnableFilter = <function> defined @Interface\AddOns\Altoholic\ItemFilters.lua:121
}
ns = <table> {
 GetNumResults = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:587
 SetClass = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:920
 SortResults = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:597
 FindItem = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:800
 FindEquipmentUpgrade = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:936
 SetCurrentItem = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:928
 Update = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:15
 GetResult = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:591
 ClearResults = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:578
 AddResult = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:583
 GetRealmsLineDesc = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:932
 GetClass = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:924
 Loots_Update = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:281
 Upgrade_Update = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:368
 SetUpdateHandler = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:19
 Realm_Update = <function> defined @Interface\AddOns\Altoholic_Search\Search.lua:277
}
currentResultType = 1
currentResultKey = <Removed>
currentResultLocation = "Bank"

**Comment by teelolws** [comment]
Its something to do with caged battle pets, but I didn't get any errors searching for them.

This should fix it: https://github.com/teelolws/Altoholic-Retail/commit/f8361d2df021f6e3c45a67cec6bf6d152ddc4451
But I won't be able to upload it to Curseforge for a while as I'm still working on other parts of the addon.

**Comment by fzarr** [comment]
I pulled down the current master branch but the bug still seems to happen with that fix. If you need me to test anything or pull any other debug info back let me know!

**Comment by teelolws** [comment]
Can you upload your altoholic and datastore saved variables. Put them in a .zip file:

![image](https://user-images.githubusercontent.com/49792789/85163575-22c02b00-b2b7-11ea-8ea2-09a8fabe5651.png)
